/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlSIBDI;
import java.awt.event.ActionListener;

/**
 *
 * @author kevin
 */
public class GUISIBDI extends javax.swing.JFrame {

    /**
     * Creates new form GUISIBDI
     */
    public GUISIBDI() {
        initComponents();
        ControlSIBDI control=new ControlSIBDI();
        escucharMenu(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jmRegistro = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmiLibros = new javax.swing.JMenuItem();
        jmiBusqueda = new javax.swing.JMenuItem();
        jmiPrestamos = new javax.swing.JMenuItem();
        jmiDevoluciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 3, 24)); // NOI18N
        jLabel1.setText("Sistema de Biblioteca SIBDI");

        jmArchivo.setText("Archivo");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiSalir);

        barraMenu.add(jmArchivo);

        jmRegistro.setText("Registros");

        jMenu1.setText("Libros");

        jmiLibros.setText("Administrar Libros");
        jmiLibros.setActionCommand("Libros");
        jmiLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLibrosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLibros);

        jmiBusqueda.setText("Busqueda Personalizada");
        jmiBusqueda.setActionCommand("Busqueda");
        jmiBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBusquedaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBusqueda);

        jmRegistro.add(jMenu1);

        jmiPrestamos.setText("Prestamos");
        jmRegistro.add(jmiPrestamos);

        jmiDevoluciones.setText("Devoluciones");
        jmRegistro.add(jmiDevoluciones);

        barraMenu.add(jmRegistro);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiLibrosActionPerformed

    private void jmiBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISIBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISIBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISIBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISIBDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISIBDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmRegistro;
    private javax.swing.JMenuItem jmiBusqueda;
    private javax.swing.JMenuItem jmiDevoluciones;
    private javax.swing.JMenuItem jmiLibros;
    private javax.swing.JMenuItem jmiPrestamos;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
    
    public void escucharMenu(ActionListener control){
        this.jmiDevoluciones.addActionListener(control);
        this.jmiLibros.addActionListener(control);
        this.jmiPrestamos.addActionListener(control);
        this.jmiSalir.addActionListener(control);
        this.jmiBusqueda.addActionListener(control);
    }
    
    
    public static final String MENU_SALIR="Salir";
    public static final String MENU_LIBRO="Libros";
    public static final String MENU_PRESTAMOS="Prestamos";
    public static final String MENU_DEVOLUCIONES="Devoluciones";
    public static final String MENU_BUSQUEDA="Busqueda";
    
}
